In [167]:
import pandas as pd
import numpy as np

In [168]:
dataframe_movies = pd.read_csv('tmdb_5000_movies.csv')
dataframe_credit = pd.read_csv('tmdb_5000_credits.csv')

In [169]:
dataframe_movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [170]:
dataframe_credit.head(5)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [171]:
# merging all the two data frame
dataframe_movies = dataframe_movies.merge(dataframe_credit, on='title')

In [172]:
del dataframe_credit

In [173]:
dataframe_movies.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [174]:
# which columns need to consider : we have to made content wise recommendation system .
# aim : is to create the tag for each movies

# 1. genre
# 2. id : used when used to make the posters
# 3. keywords : (tags)
# 4. title
# 5. cast 
# 6. crew 

# note : we only consider the column which we can use for recommendation

In [175]:
dataframe_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [176]:
dataframe_movies = dataframe_movies[[ 'id',  'title', 'genres', 'cast', 'crew','overview', 'keywords']]

In [177]:
dataframe_movies.head(3)

,id,title,genres,cast,crew,overview,keywords
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."

In [178]:
# checking for missing 
dataframe_movies.isnull().sum()

id          0
title       0
genres      0
cast        0
crew        0
overview    3
keywords    0
dtype: int64

In [179]:
dataframe_movies.dropna(inplace=True)

In [180]:
dataframe_movies.isnull().sum()

id          0
title       0
genres      0
cast        0
crew        0
overview    0
keywords    0
dtype: int64

In [181]:
# checking duplicate row
dataframe_movies.duplicated().sum()

0

In [182]:
dataframe_movies.iloc[0].genres # <-- covert all this to format ['action', 'adventure', 'fantasy']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [183]:
import ast

def convert(data):
    genre  = []

    for i in ast.literal_eval(data):
        # temp = i.name
        genre.append(i['name'])
    
    return genre

dataframe_movies['genres'] = dataframe_movies['genres'].apply(convert)
dataframe_movies.head(5)

,id,title,genres,cast,crew,overview,keywords
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,Spectre,"[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [184]:

dataframe_movies['keywords'] = dataframe_movies['keywords'].apply(convert)

In [185]:
def convert_cast(data):
    l = []
    counter = 0 
    for i in ast.literal_eval(data):
        if counter != 3 :
            l.append(i['name'])
            counter += 1
        else:
            break
    return l 

dataframe_movies['cast'] = dataframe_movies['cast'].apply(convert_cast)

In [186]:
dataframe_movies.head(1)

,id,title,genres,cast,crew,overview,keywords
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon..."

In [187]:
dataframe_movies['crew'].iloc[0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [188]:
def fetch_director(data):
    l = []
    for i in ast.literal_eval(data):
        if i['job'] == 'Director':
            l.append(i['name'])
    return l 

dataframe_movies['crew'] = dataframe_movies['crew'].apply(fetch_director)

In [189]:
dataframe_movies.head(1)

,id,title,genres,cast,crew,overview,keywords
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon..."

In [190]:
dataframe_movies['overview'] = dataframe_movies['overview'].apply(lambda x : x.split())
dataframe_movies.head(1)

,id,title,genres,cast,crew,overview,keywords
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon..."

In [191]:
# we'll concatenate the strings becase james cameron will be interpreted as different entity not a single entity for this we will apply transformation 

dataframe_movies['genres'] = dataframe_movies['genres'].apply(lambda x : [i.replace(" ", '') for i in x])
dataframe_movies['keywords'] = dataframe_movies['keywords'].apply(lambda x : [i.replace(" ", '') for i in x])
dataframe_movies['cast'] = dataframe_movies['cast'].apply(lambda x : [i.replace(" ", '') for i in x])
dataframe_movies['crew'] = dataframe_movies['crew'].apply(lambda x : [i.replace(" ", '') for i in x])

In [192]:
dataframe_movies['tags'] = dataframe_movies['genres'] + dataframe_movies['keywords'] + dataframe_movies['cast'] + dataframe_movies['crew']

In [193]:
dataframe_movies.head(1)

,id,title,genres,cast,crew,overview,keywords,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction, c..."

In [194]:
dataframe = dataframe_movies[['id', 'title','tags']]

In [195]:
dataframe.head(1)

      id   title                                               tags
0  19995  Avatar  [Action, Adventure, Fantasy, ScienceFiction, c...

In [196]:
dataframe['tags'] = dataframe['tags'].apply(lambda x : " ".join(x))

C:\Users\Abhishek\AppData\Local\Temp\ipykernel_13136\2699790778.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['tags'] = dataframe['tags'].apply(lambda x : " ".join(x))

In [197]:
dataframe.iloc[0]['tags']

'Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [198]:
dataframe['tags'] = dataframe['tags'].apply(lambda x : x.lower())

C:\Users\Abhishek\AppData\Local\Temp\ipykernel_13136\3390955714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['tags'] = dataframe['tags'].apply(lambda x : x.lower())

In [199]:
# now we'll perform the text vectorization .

In [200]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

def stem_data(text):
    lst = []
    for i in text.split() :
        lst.append(ps.stem(i))

    return " ".join(lst)

dataframe['tags'] = dataframe['tags'].apply(stem_data)

C:\Users\Abhishek\AppData\Local\Temp\ipykernel_13136\405002490.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe['tags'] = dataframe['tags'].apply(stem_data)

In [201]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [202]:
dataframe.head(1)

      id   title                                               tags
0  19995  Avatar  action adventur fantasi sciencefict culturecla...

In [203]:
vector =  cv.fit_transform(dataframe['tags']).toarray()

In [204]:
dataframe

,id,title,tags
0,19995,Avatar,action adventur fantasi sciencefict culturecla...
1,285,Pirates of the Caribbean: At World's End,adventur fantasi action ocean drugabus exotici...
2,206647,Spectre,action adventur crime spi basedonnovel secreta...
3,49026,The Dark Knight Rises,action crime drama thriller dccomic crimefight...
4,49529,John Carter,action adventur sciencefict basedonnovel mar m...
...,...,...,...
4804,9367,El Mariachi,action crime thriller unitedstates–mexicobarri...
4805,72766,Newlyweds,comedi romanc edwardburn kerrybishé marshadiet...
4806,231617,"Signed, Sealed, Delivered",comedi drama romanc tvmovi date loveatfirstsig...
4807,126186,Shanghai Calling,danielhenney elizacoup billpaxton danielhsia
4808,25975,My Date with Drew,documentari obsess camcord crush dreamgirl dre...

In [207]:
len(cv.get_feature_names_out())

5000

In [208]:
# now we find the distance here we will use cosine distance . at higher dimension euclidian distance is not a reliable solution so we ll use cosine distance

In [210]:
from sklearn.metrics.pairwise import cosine_similarity 

similarity = cosine_similarity(vector)

In [226]:
sorted(list(enumerate(similarity[0])), reverse=True, key = lambda x : x[1] ) # always hold the index simlirarity[0] mean . similiarity with respect to movie 0

[(0, 1.0000000000000004),
 (47, 0.3849001794597506),
 (2374, 0.34426518632954817),
 (61, 0.32025630761017426),
 (83, 0.3142696805273545),
 (2405, 0.30123203803835463),
 (2494, 0.29095718698132317),
 (3407, 0.29095718698132317),
 (1192, 0.29012942659282975),
 (1934, 0.29012942659282975),
 (786, 0.28867513459481287),
 (4121, 0.28867513459481287),
 (94, 0.28005601680560194),
 (4, 0.27216552697590873),
 (260, 0.27216552697590873),
 (1827, 0.27216552697590873),
 (466, 0.2721655269759087),
 (3210, 0.2721655269759087),
 (2329, 0.26688025634181195),
 (1202, 0.2649064714130087),
 (322, 0.2592592592592593),
 (1325, 0.2581988897471611),
 (2756, 0.2581988897471611),
 (3997, 0.2581988897471611),
 (4490, 0.2581988897471611),
 (81, 0.25717224993681986),
 (206, 0.25717224993681986),
 (1288, 0.25660011963983365),
 (2071, 0.25660011963983365),
 (168, 0.24845199749997662),
 (661, 0.24845199749997662),
 (490, 0.24343224778007386),
 (942, 0.24343224778007386),
 (1214, 0.24343224778007386),
 (17, 0.24077170617153845),
 (838, 0.24077170617153842),
 (41, 0.2405626121623441),
 (108, 0.2405626121623441),
 (1483, 0.23570226039551587),
 (2359, 0.23570226039551587),
 (2476, 0.23570226039551587),
 (2709, 0.23570226039551587),
 (4190, 0.23570226039551587),
 (1392, 0.2333800140046683),
 (50, 0.2321035412742638),
 (228, 0.2321035412742638),
 (371, 0.2321035412742638),
 (495, 0.2321035412742638),
 (1613, 0.2321035412742638),
 (1986, 0.2321035412742638),
 (2446, 0.2321035412742638),
 (3496, 0.2321035412742638),
 (507, 0.22680460581325726),
 (539, 0.22680460581325726),
 (931, 0.22680460581325726),
 (84, 0.22222222222222227),
 (102, 0.22222222222222227),
 (184, 0.22222222222222227),
 (859, 0.22222222222222227),
 (1045, 0.22222222222222227),
 (1087, 0.22222222222222227),
 (3091, 0.22222222222222227),
 (4405, 0.22222222222222227),
 (85, 0.22075539284417395),
 (71, 0.21821789023599236),
 (193, 0.21821789023599236),
 (2594, 0.21821789023599236),
 (3728, 0.21821789023599236),
 (3860, 0.21821789023599236),
 (4046, 0.21821789023599236),
 (4254, 0.21821789023599236),
 (278, 0.21516574145596762),
 (36, 0.21350420507344953),
 (182, 0.21350420507344953),
 (577, 0.21350420507344953),
 (777, 0.21350420507344953),
 (1193, 0.21350420507344953),
 (4336, 0.21350420507344953),
 (582, 0.20998026278290405),
 (3160, 0.20998026278290405),
 (51, 0.2057377999494559),
 (74, 0.2057377999494559),
 (126, 0.2057377999494559),
 (172, 0.2057377999494559),
 (187, 0.2057377999494559),
 (1654, 0.2057377999494559),
 (2165, 0.2057377999494559),
 (2200, 0.2057377999494559),
 (131, 0.2041241452319315),
 (457, 0.2041241452319315),
 (715, 0.2041241452319315),
 (1669, 0.2041241452319315),
 (1671, 0.2041241452319315),
 (1682, 0.2041241452319315),
 (2657, 0.2041241452319315),
 (3233, 0.2041241452319315),
 (3734, 0.2041241452319315),
 (10, 0.1987615979999813),
 (32, 0.1987615979999813),
 (939, 0.1987615979999813),
 (2682, 0.1987615979999813),
 (238, 0.19641855032959654),
 (305, 0.1924500897298753),
 (7, 0.19245008972987526),
 (72, 0.19245008972987526),
 (111, 0.19245008972987526),
 (754, 0.19245008972987526),
 (972, 0.19245008972987526),
 (1231, 0.19245008972987526),
 (1766, 0.19245008972987526),
 (2311, 0.19245008972987526),
 (2786, 0.19245008972987526),
 (2792, 0.19245008972987526),
 (3156, 0.19245008972987526),
 (3363, 0.19245008972987526),
 (3487, 0.19245008972987526),
 (3781, 0.19245008972987526),
 (4146, 0.19245008972987526),
 (4213, 0.19245008972987526),
 (4320, 0.19245008972987526),
 (4560, 0.19245008972987526),
 (4657, 0.19245008972987526),
 (4737, 0.19245008972987526),
 (91, 0.19245008972987523),
 (315, 0.19245008972987523),
 (412, 0.19245008972987523),
 (467, 0.19245008972987523),
 (535, 0.19245008972987523),
 (773, 0.19245008972987523),
 (1094, 0.19245008972987523),
 (1273, 0.19245008972987523),
 (1278, 0.19245008972987523),
 (1304, 0.19245008972987523),
 (1327, 0.19245008972987523),
 (1440, 0.19245008972987523),
 (1571, 0.19245008972987523),
 (1894, 0.19245008972987523),
 (2131, 0.19245008972987523),
 (2163, 0.19245008972987523),
 (2579, 0.19245008972987523),
 (3554, 0.19245008972987523),
 (3814, 0.19245008972987523),
 (14, 0.18670401120373464),
 (52, 0.18670401120373464),
 (232, 0.18670401120373464),
 (300, 0.18670401120373464),
 (799, 0.18670401120373464),
 (1297, 0.18670401120373464),
 (97, 0.18257418583505539),
 (304, 0.18257418583505539),
 (368, 0.18257418583505539),
 (486, 0.18257418583505539),
 (543, 0.18257418583505539),
 (746, 0.18257418583505539),
 (920, 0.18257418583505539),
 (1000, 0.18257418583505539),
 (1520, 0.18257418583505539),
 (1804, 0.18257418583505539),
 (1916, 0.18257418583505539),
 (1941, 0.18257418583505539),
 (2319, 0.18257418583505539),
 (4348, 0.18257418583505539),
 (31, 0.1814436846506058),
 (46, 0.1814436846506058),
 (127, 0.1814436846506058),
 (129, 0.1814436846506058),
 (151, 0.1814436846506058),
 (207, 0.1814436846506058),
 (266, 0.1814436846506058),
 (342, 0.1814436846506058),
 (778, 0.1814436846506058),
 (870, 0.1814436846506058),
 (973, 0.1814436846506058),
 (2129, 0.1814436846506058),
 (3536, 0.1814436846506058),
 (19, 0.17660431427533915),
 (26, 0.17660431427533915),
 (166, 0.17660431427533915),
 (587, 0.17660431427533915),
 (1533, 0.17660431427533915),
 (18, 0.17407765595569785),
 (56, 0.17407765595569785),
 (86, 0.17407765595569785),
 (157, 0.17407765595569785),
 (208, 0.17407765595569785),
 (241, 0.17407765595569785),
 (294, 0.17407765595569785),
 (362, 0.17407765595569785),
 (379, 0.17407765595569785),
 (472, 0.17407765595569785),
 (581, 0.17407765595569785),
 (627, 0.17407765595569785),
 (791, 0.17407765595569785),
 (814, 0.17407765595569785),
 (1002, 0.17407765595569785),
 (1493, 0.17407765595569785),
 (1824, 0.17407765595569785),
 (1874, 0.17407765595569785),
 (1920, 0.17407765595569785),
 (1938, 0.17407765595569785),
 (1975, 0.17407765595569785),
 (2392, 0.17407765595569785),
 (2558, 0.17407765595569785),
 (2697, 0.17407765595569785),
 (2864, 0.17407765595569785),
 (2869, 0.17407765595569785),
 (2997, 0.17407765595569785),
 (3374, 0.17407765595569785),
 (3618, 0.17407765595569785),
 (158, 0.17213259316477408),
 (169, 0.17213259316477408),
 (740, 0.17213259316477408),
 (1084, 0.17213259316477408),
 (1476, 0.17213259316477408),
 (2852, 0.17213259316477408),
 (3216, 0.17213259316477408),
 (3331, 0.17213259316477408),
 (3439, 0.17213259316477408),
 (3744, 0.17213259316477408),
 (3760, 0.17213259316477408),
 (3908, 0.17213259316477408),
 (3933, 0.17213259316477408),
 (4008, 0.17213259316477408),
 (150, 0.16798421022632323),
 (160, 0.16798421022632323),
 (813, 0.16798421022632323),
 (1992, 0.16798421022632323),
 (3352, 0.16798421022632323),
 (38, 0.16666666666666669),
 (67, 0.16666666666666669),
 (121, 0.16666666666666669),
 (132, 0.16666666666666669),
 (220, 0.16666666666666669),
 (224, 0.16666666666666669),
 (307, 0.16666666666666669),
 (389, 0.16666666666666669),
 (400, 0.16666666666666669),
 (487, 0.16666666666666669),
 (511, 0.16666666666666669),
 (541, 0.16666666666666669),
 (624, 0.16666666666666669),
 (836, 0.16666666666666669),
 (935, 0.16666666666666669),
 (1029, 0.16666666666666669),
 (1320, 0.16666666666666669),
 (1475, 0.16666666666666669),
 (2048, 0.16666666666666669),
 (2492, 0.16666666666666669),
 (3325, 0.16666666666666669),
 (55, 0.16412198797244362),
 (491, 0.16412198797244362),
 (654, 0.16412198797244362),
 (1080, 0.16412198797244362),
 (28, 0.16051447078102563),
 (149, 0.16051447078102563),
 (501, 0.16051447078102563),
 (1069, 0.16051447078102563),
 (9, 0.16012815380508716),
 (59, 0.16012815380508716),
 (70, 0.16012815380508716),
 (203, 0.16012815380508716),
 (229, 0.16012815380508716),
 (292, 0.16012815380508716),
 (295, 0.16012815380508716),
 (483, 0.16012815380508716),
 (505, 0.16012815380508716),
 (589, 0.16012815380508716),
 (607, 0.16012815380508716),
 (643, 0.16012815380508716),
 (660, 0.16012815380508716),
 (732, 0.16012815380508716),
 (898, 0.16012815380508716),
 (1140, 0.16012815380508716),
 (1176, 0.16012815380508716),
 (1200, 0.16012815380508716),
 (1267, 0.16012815380508716),
 (1323, 0.16012815380508716),
 (1497, 0.16012815380508716),
 (1717, 0.16012815380508716),
 (1829, 0.16012815380508716),
 (1879, 0.16012815380508716),
 (2001, 0.16012815380508716),
 (2068, 0.16012815380508716),
 (2816, 0.16012815380508716),
 (381, 0.15713484026367724),
 (518, 0.15713484026367724),
 (610, 0.15713484026367724),
 (618, 0.15713484026367724),
 (678, 0.15713484026367724),
 (960, 0.15713484026367724),
 (1307, 0.15713484026367724),
 (1310, 0.15713484026367724),
 (1449, 0.15713484026367724),
 (1630, 0.15713484026367724),
 (2354, 0.15713484026367724),
 (2616, 0.15713484026367724),
 (2974, 0.15713484026367724),
 (3320, 0.15713484026367724),
 (3426, 0.15713484026367724),
 (3719, 0.15713484026367724),
 (3779, 0.15713484026367724),
 (4095, 0.15713484026367724),
 (4132, 0.15713484026367724),
 (4158, 0.15713484026367724),
 (4319, 0.15713484026367724),
 (4339, 0.15713484026367724),
 (4353, 0.15713484026367724),
 (4431, 0.15713484026367724),
 (4453, 0.15713484026367724),
 (4502, 0.15713484026367724),
 (4654, 0.15713484026367724),
 (33, 0.15430334996209194),
 (39, 0.15430334996209194),
 (79, 0.15430334996209194),
 (101, 0.15430334996209194),
 (233, 0.15430334996209194),
 (249, 0.15430334996209194),
 (311, 0.15430334996209194),
 (332, 0.15430334996209194),
 (373, 0.15430334996209194),
 (413, 0.15430334996209194),
 (612, 0.15430334996209194),
 (728, 0.15430334996209194),
 (781, 0.15430334996209194),
 (977, 0.15430334996209194),
 (978, 0.15430334996209194),
 (1111, 0.15430334996209194),
 (1156, 0.15430334996209194),
 (1199, 0.15430334996209194),
 (1342, 0.15430334996209194),
 (1688, 0.15430334996209194),
 (2177, 0.15430334996209194),
 (2345, 0.15430334996209194),
 (2517, 0.15430334996209194),
 (4468, 0.15430334996209194),
 (190, 0.1543033499620919),
 (1723, 0.1543033499620919),
 (1292, 0.15396007178390023),
 (1435, 0.15396007178390023),
 (27, 0.14907119849998599),
 (37, 0.14907119849998599),
 (138, 0.14907119849998599),
 (426, 0.14907119849998599),
 (665, 0.14907119849998599),
 (1401, 0.14907119849998599),
 (1492, 0.14907119849998599),
 (1955, 0.14907119849998599),
 (2968, 0.14907119849998599),
 (3626, 0.14907119849998599),
 (3905, 0.14907119849998599),
 (2391, 0.14814814814814817),
 (302, 0.14547859349066158),
 (600, 0.14547859349066158),
 (776, 0.14547859349066158),
 (1247, 0.14547859349066158),
 (1274, 0.14547859349066158),
 (1290, 0.14547859349066158),
 (1299, 0.14547859349066158),
 (1603, 0.14547859349066158),
 (1978, 0.14547859349066158),
 (2108, 0.14547859349066158),
 (2116, 0.14547859349066158),
 (2124, 0.14547859349066158),
 (2246, 0.14547859349066158),
 (2508, 0.14547859349066158),
 (2655, 0.14547859349066158),
 (3186, 0.14547859349066158),
 (3375, 0.14547859349066158),
 (3609, 0.14547859349066158),
 (3830, 0.14547859349066158),
 (3858, 0.14547859349066158),
 (3992, 0.14547859349066158),
 (4088, 0.14547859349066158),
 (4163, 0.14547859349066158),
 (4179, 0.14547859349066158),
 (4473, 0.14547859349066158),
 (4516, 0.14547859349066158),
 (4624, 0.14547859349066158),
 (4626, 0.14547859349066158),
 (122, 0.14433756729740643),
 (242, 0.14433756729740643),
 (369, 0.14433756729740643),
 (420, 0.14433756729740643),
 (508, 0.14433756729740643),
 (768, 0.14433756729740643),
 (922, 0.14433756729740643),
 (1508, 0.14433756729740643),
 (1752, 0.14433756729740643),
 (3307, 0.14433756729740643),
 (3468, 0.14433756729740643),
 (16, 0.140028008402801),
 (20, 0.140028008402801),
 (35, 0.140028008402801),
 (63, 0.140028008402801),
 (68, 0.140028008402801),
 (88, 0.140028008402801),
 (96, 0.140028008402801),
 (230, 0.140028008402801),
 (279, 0.140028008402801),
 (403, 0.140028008402801),
 (503, 0.140028008402801),
 (547, 0.140028008402801),
 (1017, 0.140028008402801),
 (1154, 0.140028008402801),
 (1619, 0.140028008402801),
 (2782, 0.140028008402801),
 (3620, 0.140028008402801),
 (183, 0.1382602259640567),
 (30, 0.13608276348795437),
 (112, 0.13608276348795437),
 (174, 0.13608276348795437),
 (275, 0.13608276348795437),
 (419, 0.13608276348795437),
 (579, 0.13608276348795437),
 (591, 0.13608276348795437),
 (1013, 0.13608276348795437),
 (1144, 0.13608276348795437),
 (1295, 0.13608276348795437),
 (1379, 0.13608276348795437),
 (2827, 0.13608276348795437),
 (3441, 0.13608276348795437),
 (3447, 0.13608276348795437),
 (4077, 0.13608276348795437),
 (48, 0.13608276348795434),
 (309, 0.13608276348795434),
 (461, 0.13608276348795434),
 (479, 0.13608276348795434),
 (668, 0.13608276348795434),
 (990, 0.13608276348795434),
 (1003, 0.13608276348795434),
 (1075, 0.13608276348795434),
 (1260, 0.13608276348795434),
 (1271, 0.13608276348795434),
 (1455, 0.13608276348795434),
 (1601, 0.13608276348795434),
 (1610, 0.13608276348795434),
 (1711, 0.13608276348795434),
 (1737, 0.13608276348795434),
 (1743, 0.13608276348795434),
 (1880, 0.13608276348795434),
 (2049, 0.13608276348795434),
 (2066, 0.13608276348795434),
 (2247, 0.13608276348795434),
 (2322, 0.13608276348795434),
 (2484, 0.13608276348795434),
 (2646, 0.13608276348795434),
 (2807, 0.13608276348795434),
 (2901, 0.13608276348795434),
 (2902, 0.13608276348795434),
 (3023, 0.13608276348795434),
 (3053, 0.13608276348795434),
 (3064, 0.13608276348795434),
 (3089, 0.13608276348795434),
 (3100, 0.13608276348795434),
 (3135, 0.13608276348795434),
 (3138, 0.13608276348795434),
 (3230, 0.13608276348795434),
 (3321, 0.13608276348795434),
 (3398, 0.13608276348795434),
 (3404, 0.13608276348795434),
 (3524, 0.13608276348795434),
 (3653, 0.13608276348795434),
 (3689, 0.13608276348795434),
 (3706, 0.13608276348795434),
 (3924, 0.13608276348795434),
 (3947, 0.13608276348795434),
 (4060, 0.13608276348795434),
 (4133, 0.13608276348795434),
 (4149, 0.13608276348795434),
 (4164, 0.13608276348795434),
 (4329, 0.13608276348795434),
 (4403, 0.13608276348795434),
 (4420, 0.13608276348795434),
 (4434, 0.13608276348795434),
 (4469, 0.13608276348795434),
 (4492, 0.13608276348795434),
 (4549, 0.13608276348795434),
 (4602, 0.13608276348795434),
 (4604, 0.13608276348795434),
 (4630, 0.13608276348795434),
 (4711, 0.13608276348795434),
 (4754, 0.13608276348795434),
 (4766, 0.13608276348795434),
 (4772, 0.13608276348795434),
 (125, 0.13400504203456162),
 (3145, 0.13400504203456162),
 (334, 0.13245323570650436),
 (410, 0.13245323570650436),
 (572, 0.13245323570650436),
 (755, 0.13245323570650436),
 (900, 0.13245323570650436),
 (1338, 0.13245323570650436),
 (1470, 0.13245323570650436),
 (2435, 0.13245323570650436),
 (2914, 0.13245323570650436),
 (2969, 0.13245323570650436),
 (4673, 0.13245323570650436),
 (2828, 0.1320196723968899),
 (2382, 0.1301200097264711),
 (25, 0.12909944487358055),
 (43, 0.12909944487358055),
 (107, 0.12909944487358055),
 (270, 0.12909944487358055),
 (271, 0.12909944487358055),
 (510, 0.12909944487358055),
 (1035, 0.12909944487358055),
 (1628, 0.12909944487358055),
 (95, 0.12830005981991682),
 (148, 0.12830005981991682),
 (167, 0.12830005981991682),
 (189, 0.12830005981991682),
 (205, 0.12830005981991682),
 (257, 0.12830005981991682),
 (308, 0.12830005981991682),
 (312, 0.12830005981991682),
 (458, 0.12830005981991682),
 (476, 0.12830005981991682),
 (530, 0.12830005981991682),
 (534, 0.12830005981991682),
 (674, 0.12830005981991682),
 (831, 0.12830005981991682),
 (1083, 0.12830005981991682),
 (1138, 0.12830005981991682),
 (1235, 0.12830005981991682),
 (1291, 0.12830005981991682),
 (1450, 0.12830005981991682),
 (1484, 0.12830005981991682),
 (1582, 0.12830005981991682),
 (1645, 0.12830005981991682),
 (1647, 0.12830005981991682),
 (1736, 0.12830005981991682),
 (1779, 0.12830005981991682),
 (2155, 0.12830005981991682),
 (2157, 0.12830005981991682),
 (2207, 0.12830005981991682),
 (2209, 0.12830005981991682),
 (2260, 0.12830005981991682),
 (2313, 0.12830005981991682),
 (2335, 0.12830005981991682),
 (2488, 0.12830005981991682),
 (2727, 0.12830005981991682),
 (2955, 0.12830005981991682),
 (2988, 0.12830005981991682),
 (3003, 0.12830005981991682),
 (3026, 0.12830005981991682),
 (3239, 0.12830005981991682),
 (3762, 0.12830005981991682),
 (3820, 0.12830005981991682),
 (4196, 0.12830005981991682),
 (4357, 0.12830005981991682),
 (4429, 0.12830005981991682),
 (4538, 0.12830005981991682),
 (4568, 0.12830005981991682),
 (5, 0.12598815766974242),
 (12, 0.12598815766974242),
 (243, 0.12598815766974242),
 (1441, 0.12598815766974242),
 (1585, 0.12598815766974242),
 (2159, 0.12598815766974242),
 (2300, 0.12598815766974242),
 (1, 0.12309149097933272),
 (76, 0.12309149097933272),
 (103, 0.12309149097933272),
 (199, 0.12309149097933272),
 (937, 0.12309149097933272),
 (2759, 0.12309149097933272),
 (2899, 0.12309149097933272),
 (62, 0.12171612389003693),
 (75, 0.12171612389003693),
 (147, 0.12171612389003693),
 (164, 0.12171612389003693),
 (195, 0.12171612389003693),
 (219, 0.12171612389003693),
 (222, 0.12171612389003693),
 (223, 0.12171612389003693),
 (237, 0.12171612389003693),
 (319, 0.12171612389003693),
 (376, 0.12171612389003693),
 (411, 0.12171612389003693),
 (471, 0.12171612389003693),
 (537, 0.12171612389003693),
 (540, 0.12171612389003693),
 (602, 0.12171612389003693),
 (664, 0.12171612389003693),
 (710, 0.12171612389003693),
 (800, 0.12171612389003693),
 (894, 0.12171612389003693),
 (1054, 0.12171612389003693),
 (1147, 0.12171612389003693),
 (1184, 0.12171612389003693),
 (1321, 0.12171612389003693),
 (1414, 0.12171612389003693),
 (1430, 0.12171612389003693),
 (1519, 0.12171612389003693),
 (1579, 0.12171612389003693),
 (1617, 0.12171612389003693),
 (1652, 0.12171612389003693),
 (1745, 0.12171612389003693),
 (1796, 0.12171612389003693),
 (1979, 0.12171612389003693),
 (2052, 0.12171612389003693),
 (2059, 0.12171612389003693),
 (2208, 0.12171612389003693),
 (2502, 0.12171612389003693),
 (2529, 0.12171612389003693),
 (2567, 0.12171612389003693),
 (2580, 0.12171612389003693),
 (2635, 0.12171612389003693),
 (2641, 0.12171612389003693),
 (2653, 0.12171612389003693),
 (2656, 0.12171612389003693),
 (2758, 0.12171612389003693),
 (2847, 0.12171612389003693),
 (3057, 0.12171612389003693),
 (3067, 0.12171612389003693),
 (3088, 0.12171612389003693),
 (3226, 0.12171612389003693),
 (3387, 0.12171612389003693),
 (3581, 0.12171612389003693),
 (3619, 0.12171612389003693),
 (3799, 0.12171612389003693),
 (3804, 0.12171612389003693),
 (3998, 0.12171612389003693),
 (4331, 0.12171612389003693),
 (82, 0.12038585308576921),
 (212, 0.12038585308576921),
 (329, 0.12038585308576921),
 (330, 0.12038585308576921),
 (4228, 0.12038585308576921),
 (123, 0.11878277418329973),
 (92, 0.11785113019775793),
 (98, 0.11785113019775793),
 (262, 0.11785113019775793),
 (363, 0.11785113019775793),
 (812, 0.11785113019775793),
 (1697, 0.11785113019775793),
 (49, 0.1160517706371319),
 (87, 0.1160517706371319),
 (105, 0.1160517706371319),
 (170, 0.1160517706371319),
 (179, 0.1160517706371319),
 (253, 0.1160517706371319),
 (306, 0.1160517706371319),
 (340, 0.1160517706371319),
 (375, 0.1160517706371319),
 (443, 0.1160517706371319),
 (555, 0.1160517706371319),
 (595, 0.1160517706371319),
 (604, 0.1160517706371319),
 (629, 0.1160517706371319),
 (653, 0.1160517706371319),
 (687, 0.1160517706371319),
 (731, 0.1160517706371319),
 (888, 0.1160517706371319),
 (908, 0.1160517706371319),
 (1009, 0.1160517706371319),
 (1086, 0.1160517706371319),
 (1218, 0.1160517706371319),
 (1246, 0.1160517706371319),
 (1257, 0.1160517706371319),
 (1280, 0.1160517706371319),
 (1301, 0.1160517706371319),
 (1361, 0.1160517706371319),
 (1382, 0.1160517706371319),
 (1462, 0.1160517706371319),
 (1548, 0.1160517706371319),
 (1819, 0.1160517706371319),
 (2056, 0.1160517706371319),
 (2105, 0.1160517706371319),
 (2161, 0.1160517706371319),
 (2205, 0.1160517706371319),
 (2243, 0.1160517706371319),
 (2377, 0.1160517706371319),
 (2630, 0.1160517706371319),
 (2767, 0.1160517706371319),
 (2797, 0.1160517706371319),
 (2966, 0.1160517706371319),
 (2998, 0.1160517706371319),
 (3015, 0.1160517706371319),
 (3753, 0.1160517706371319),
 (3903, 0.1160517706371319),
 (4097, 0.1160517706371319),
 (4640, 0.1160517706371319),

In [ ]:
# fetch the index of the movie 

dataframe[dataframe['title'] == 'Batman Begins'].index[0]

119

In [233]:
def recommend(movie):
    movie_list = []
    
    movie_index = dataframe[dataframe['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key = lambda x : x[1] )[1:6]

    for i in movie_list :
        print(dataframe.iloc[i[0]]['title'])
    return

recommend('Batman')

Batman
Batman & Robin
Batman Returns
Batman
Batman v Superman: Dawn of Justice